# config/mongodb.yml
base: &base
  adapter: mongodb
  database: sunaodb
#These are needed to authenticate with your db
#should it run on another server
  host: localhost
#  username: your-username
#  password: your-password

development:
  <<: *base

test:
  <<: *base
  database: sunaodb-test


production:
  <<: *base
